# Generated by Django 3.2 on 2021-09-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='assignees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='reviewers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
